--
-- PostgreSQL database dump
--

\restrict p33UeuI0F1Ltak8GDaVMCb5jroQ8SIxoU65ANSsGBAYF5Cz17zfOhskyh2kJMMN

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: characters; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (7, 'Верховный Смотритель Кэмпбелл', 'Смотритель', 'Вечнопритоки', 'Dishonored', '/assets/img/characters/campbell.png', 'Глава Ордена Аббатства Вечного Хора. Религиозный фанатик и заговорщик. Участвовал в убийстве императрицы. Использовал Орден для своих политических целей.', '{"Во имя Аббатства!","Еретики должны быть наказаны","Аутсайдер - источник всего зла"}', 'Убит или заклеймён как еретик', '2026-01-31 03:04:15.555579', 'Дэниел Хейген', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (9, 'Эмили Калдвин', 'Дочь императрицы', 'Империя', 'Dishonored', '/assets/img/characters/emily_child.png', 'Дочь императрицы Джесамин Калдвин и Корво Аттано. После смерти матери находилась под опекой Корво. Наследница трона Островной Империи. Стала свидетелем убийства матери.', '{"Корво! Я знала, что ты придёшь!","Расскажи мне про маму","Когда я стану императрицей, всё будет по-другому"}', 'Жива', '2026-01-31 03:04:15.555579', 'Хлоя Грэйс Морец', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (11, 'Делайла Копперспун', 'Самозванка-императрица', 'Ведьмы Бригмора', 'Dishonored 2', '/assets/img/characters/delilah.png', 'Самозванка-императрица, обладающая магическими способностями. Сводная сестра Джесамин Калдвин. Захватила трон с помощью колдовства и превратила Дунвольд в кошмар.', '{"Я создам мир по своему образу","Трон принадлежит мне по праву рождения","Они забыли обо мне, но я не забыла"}', 'Побеждена Эмили/Корво', '2026-01-31 03:04:15.561037', 'Пола Маркс', 'Dishonored: DLC (упоминание)', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (12, 'Киррин Джиндош', 'Изобретатель', 'Независимый', 'Dishonored 2', '/assets/img/characters/jindosh.png', 'Гениальный изобретатель и учёный Карнаки. Создатель Клокворк-солдат. Служит Делайле. Его особняк полон механических ловушек и изобретений.', '{"Совершенство механики!","Мои творения непобедимы","Наука превыше всего"}', 'Убит или лишён разума', '2026-01-31 03:04:15.561037', 'Педро Паскаль', 'Dishonored 2', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (13, 'Брендан Байрн', 'Глава Великой стражи', 'Вечнопритоки', 'Dishonored 2', '/assets/img/characters/byrne.png', 'Герцог Серконоса, правитель южных земель. Союзник Делайлы. Организовал переворот против Эмили. Устраивает жестокие кровавые бои.', '{"Добро пожаловать в Серконос","Здесь правлю я","Кровь и власть - вот что важно"}', 'Убит или свергнут', '2026-01-31 03:04:15.561037', 'Сэм Рокуэлл', 'Dishonored 2', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (15, 'Миган Фостер', 'Капитан', 'Вечнопритоки', 'Dishonored 2', '/assets/img/characters/meagan.png', 'Капитан корабля "Ужасный Герцог", на самом деле Билли Лёрк под псевдонимом. Помогает Эмили и Корво сбежать из Дунвольда.', '{"На корабль! Быстрее!","Море - мой дом","Доверьтесь мне"}', 'Жива (на самом деле Билли Лёрк)', '2026-01-31 03:04:15.561037', 'Розарио Доусон', 'Dishonored 2', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (16, 'Аутсайдер', 'Божество пустоты', 'Независимая', 'Dishonored 2', '/assets/img/characters/outsider2.png', 'Загадочное божество Бездны. Продолжает наблюдать за судьбами избранных. Дарует Эмили её уникальные способности, если она принимает его дар.', '{"Интересно, что ты выберешь на этот раз","Империя в огне. Что ты будешь делать?","Твоя судьба - в твоих руках"}', 'Бессмертен', '2026-01-31 03:04:15.561037', 'Робин Лорд Тейлор', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (2, 'Аутсайдер', 'Божество пустоты', 'Независимая', 'Dishonored', '/assets/img/characters/outsider.png', 'Загадочное божество Бездны, существующее вне времени и пространства. Дарует избранным смертным сверхъестественные способности, наблюдая за их судьбами. Проявляет интерес к Корво Аттано и его выборам.', '{"Твоё сердце бьётся чаще, когда я рядом","Я дам тебе силу. Что ты с ней сделаешь - твой выбор","Наблюдать за тобой... интересно"}', 'Бессмертен', '2026-01-31 03:04:15.555579', 'Билли Люш', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (4, 'Пьеро Джоплин', 'Королевский врач', 'Верные', 'Dishonored', '/assets/img/characters/piero.png', 'Королевский врач и изобретатель. Гений механики и алхимии. Создатель многих устройств для Корво, включая складную маску и улучшения оружия. Член группы Лоялистов.', '{"Наука и магия - две стороны одной медали","Я создал для вас кое-что интересное","Эти изобретения помогут вам в миссии"}', 'Жив', '2026-01-31 03:04:15.555579', 'Брэд Дуриф', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (5, 'Антон Соколов', 'Художник и учёный', 'Китобои', 'Dishonored', '/assets/img/characters/sokolov.png', 'Королевский врач, художник, философ и учёный. Гений своего времени. Работал на лорда-регента, изучая чуму. Позже помогал Корво в его миссии возмездия. Создатель многих изобретений.', '{"Соколов создал это!","Я посвятил жизнь изучению природы вещей","Искусство и наука неразделимы"}', 'Жив', '2026-01-31 03:04:15.555579', 'Роджер Л. Джексон', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (19, 'Эмили Калдвин', 'Императрица', 'Империя', 'Dishonored 2', '/assets/img/characters/emily.png', 'Дочь Корво Аттано и Джесамин Калдвин. Императрица Островной Империи. После государственного переворота была вынуждена бежать из Дунволла. Обладает уникальными способностями, дарованными Аутсайдером.', '{"Мне не нужна корона, чтобы быть сильной","Я не просто императрица. Я воин","Они забыли, что я дочь Корво Аттано"}', 'Жива', '2026-01-31 03:04:15.561037', 'Эрика Латтрелл', 'Dishonored (ребенок)', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (17, 'Корво Аттано', 'Королевский защитник', 'Империя', 'Dishonored 2', '/assets/img/characters/corvo2.png', 'Королевский Защитник, отец Эмили Калдвин. Легендарный убийца, который остановил заговор лорда-регента. Теперь защищает свою дочь и помогает вернуть ей трон.', '{"Я защищал императрицу. Теперь защищаю свою дочь","Месть - это то, чем я занимаюсь лучше всего","За Эмили"}', 'Жив', '2026-01-31 03:04:15.561037', 'Стивен Рассел', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (10, 'Билли Лёрк', 'Капитан корабля', 'Независимая', 'Dishonored 2', '/assets/img/characters/billie.png', 'Бывшая правая рука Дауда, капитан корабля "Трепанация". Помогает Эмили и Корво в их миссии вернуть трон. Потеряла руку и глаз в прошлом.', '{"Готовы отплывать?","Я многое повидала, но это...","Дауд многому меня научил"}', 'Жива', '2026-01-31 03:04:15.561037', 'Розарио Доусон', 'Dishonored 2', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (14, 'Александрия Хайпейша', 'Доктор', 'Культ Аутсайдера', 'Dishonored 2', '/assets/img/characters/hypatia.png', 'Доктор и алхимик Аддермайрского института. Создала раствор Аддермайра. Проводит жестокие эксперименты над пациентами по приказу короны.', '{"Во имя науки","Прогресс требует жертв","Мои исследования важнее всего"}', 'Убита или арестована', '2026-01-31 03:04:15.561037', 'Андреа Райзборо', 'Dishonored 2', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (18, 'Антон Соколов', 'Художник и учёный', 'Независимая', 'Dishonored 2', '/assets/img/characters/sokolov2.png', 'Легендарный учёный, художник и изобретатель. Теперь пожилой, но всё ещё гениальный. Помогает Эмили и Корво советами и изобретениями.', '{"Годы не остановили мой разум","Я всё ещё могу удивить мир","Эмили, ты выросла сильной"}', 'Жив', '2026-01-31 03:04:15.561037', 'Роджер Л. Джексон', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (3, 'Дауд', 'Наёмный убийца', 'Китобои', 'Dishonored', '/assets/img/characters/daud.png', 'Легендарный убийца, лидер китобоев. Убил императрицу Джесамин Калдвин по заказу. Позже раскаялся в содеянном и пытался искупить свою вину.', '{"Моё имя - Дауд. И я убил императрицу","Я много убивал. Но это убийство изменило всё","Искупление... возможно ли оно для таких, как я?"}', 'Жив (на момент Dishonored 2)', '2026-01-31 03:04:15.555579', 'Майкл Мадсен', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (1, 'Корво Аттано', 'Королевский защитник', 'Лоялисты', 'Dishonored', '/assets/img/characters/corvo.png', 'Королевский Защитник императрицы Джесамин Калдвин. Ложно обвинён в её убийстве и заключён в тюрьму Колдридж. Сбегает с помощью Лоялистов и получает силы от Аутсайдера, чтобы отомстить заговорщикам.', '{"За императрицу","Месть решает всё","Я был обманут. Преда"}', 'Жив', '2026-01-31 03:04:15.555579', 'Не озвучен (Dishonored 1)', 'Dishonored', NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (6, 'Адмирал Хавлок', 'Адмирал флота', 'Верные', 'Dishonored', '/assets/img/characters/havelock.png', NULL, NULL, 'Мертв', '2026-01-31 03:04:15.555579', NULL, NULL, NULL);
INSERT INTO public.characters (id, name, role, faction, game, image, description, quotes, status, created_at, voice_actor, first_appearance, faction_id) VALUES (8, 'Грэнни Тряпки', 'Ведьма', 'Ведьмы Бригмора', 'Dishonored', '/assets/img/characters/granny.png', NULL, NULL, 'Мертв', '2026-01-31 03:04:15.555579', NULL, NULL, NULL);


--
-- Data for Name: factions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.factions (id, name, game, description, leader, headquarters, image, created_at) VALUES (1, 'Верные', 'Dishonored', 'Группа заговорщиков, стремящихся свергнуть Лорда-Регента и вернуть Эмили на трон.', 'Адмирал Хавлок', 'Паб "Гончие Ямы"', NULL, '2026-01-31 00:34:17.794492');
INSERT INTO public.factions (id, name, game, description, leader, headquarters, image, created_at) VALUES (2, 'Китобои', 'Dishonored', 'Могущественная промышленная гильдия, занимающаяся добычей китового жира - основного источника энергии Империи.', 'Соколов', 'Китобойная станция Рудшор', NULL, '2026-01-31 00:34:17.794492');
INSERT INTO public.factions (id, name, game, description, leader, headquarters, image, created_at) VALUES (3, 'Вечнозрители', 'Dishonored', 'Религиозный орден, поклоняющийся Вечнозрителю и борющийся с магией и ересью.', 'Верховный Смотритель Кэмпбелл', 'Высокое Аббатство', NULL, '2026-01-31 00:34:17.794492');
INSERT INTO public.factions (id, name, game, description, leader, headquarters, image, created_at) VALUES (4, 'Убийцы Даудю', 'Dishonored', 'Элитная группа наёмных убийц под командованием Даудю, наделённых силами Аутсайдера.', 'Даудю', 'Скотобойня', NULL, '2026-01-31 00:34:17.794492');
INSERT INTO public.factions (id, name, game, description, leader, headquarters, image, created_at) VALUES (5, 'Герцогская гвардия', 'Dishonored 2', 'Военизированная полиция Карнаки под контролем Делайлы Копперспун.', 'Делайла Копперспун', 'Особняк герцога', NULL, '2026-01-31 00:34:17.794492');
INSERT INTO public.factions (id, name, game, description, leader, headquarters, image, created_at) VALUES (6, 'Алая стража', 'Dishonored 2', 'Королевская гвардия Дануолла и личные телохранители Императрицы.', 'Императрица Эмили', 'Башня Дануолла', NULL, '2026-01-31 00:34:17.794492');
INSERT INTO public.factions (id, name, game, description, leader, headquarters, image, created_at) VALUES (7, 'Аббатство Вечнозрителей', 'Dishonored 2', 'Продолжение религиозного ордена, но с новыми взглядами после событий первой игры.', 'Верховная Смотрительница Байрн', 'Храм Карнаки', NULL, '2026-01-31 00:34:17.794492');


--
-- Data for Name: game_mechanics; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (2, 'Стелс-геймплей', 'stealth', 'Dishonored', 'Скрытность - ключ к успеху. Избегайте обнаружения, используя тени, способности и окружение.', '{"Обнаружение повышает сложность","Тени скрывают от врагов","Звуки привлекают внимание","Разные пути прохождения уровней"}', '{"Используйте Тёмное зрение для планирования","Ждите патрули врагов","Перемещайтесь по крышам","Отключайте источники света"}', '2026-01-31 00:34:17.811333', NULL);
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (3, 'Достижения Ghost и Clean Hands', 'achievements', 'Dishonored', 'Особые достижения за прохождение без убийств и обнаружений.', '{"Ghost: не быть замеченным","Clean Hands: никого не убивать","Требует идеального планирования","Награждается уникальными концовками"}', '{"Сохраняйтесь часто","Изучайте карты перед действием","Используйте способности для стелса","Нокаутированные враги не считаются убийством"}', '2026-01-31 00:34:17.811333', NULL);
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (5, 'Руны и улучшения', 'progression', 'Dishonored', 'Руны используются для получения и улучшения сверхъестественных способностей.', '{"Находятся с помощью Сердца","Каждая способность имеет уровни","Ограниченное количество рун в игре","Влияют на стиль прохождения"}', '{"Планируйте развитие заранее","Исследуйте уровни полностью","Разные билды для разных стилей"}', '2026-01-31 00:34:17.811333', NULL);
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (1, 'Система Хаоса', 'chaos', 'Dishonored', 'Уровень хаоса определяет мир вокруг вас и влияет на концовку игры. Чем больше людей вы убиваете, тем выше хаос.', '{"Низкий хаос: меньше крыс и жуков, светлая концовка","Высокий хаос: больше врагов, тёмная концовка","Влияет на поведение союзников","Изменяет диалоги и реакции NPC"}', '{"Используйте нелетальные методы для низкого хаоса","Прячьте тела убитых врагов","Используйте сон-дротики вместо смертельных"}', '2026-01-31 00:34:17.811333', '/assets/img/mechanics/chaos.png');
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (4, 'Костяные амулеты', 'customization', 'Dishonored', 'Магические амулеты, дающие пассивные бонусы и улучшения.', '{"Находятся по всему миру","Дают различные пассивные эффекты","Можно носить до 6 одновременно","В D2 можно создавать собственные"}', '{"Используйте Сердце для поиска амулетов","Выбирайте амулеты под свой стиль игры","Комбинируйте эффекты для синергии"}', '2026-01-31 00:34:17.811333', '/assets/img/mechanics/bone_charms.png');
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (6, 'Система Хаоса', 'chaos', 'Dishonored 2', 'Улучшенная система хаоса с более детализированным влиянием на мир. Каждое убийство и обнаружение влияет на концовку игры.', '{"Низкий хаос: меньше врагов, светлая концовка","Высокий хаос: больше кровомух и крыс, тёмная концовка","Влияет на диалоги и реакции персонажей","Более детальная система чем в первой игре"}', '{"Используйте нелетальные методы для низкого хаоса","Прячьте тела убитых врагов","Избегайте случайных убийств","Используйте усыпляющие дротики"}', '2026-01-31 06:03:13.892902', NULL);
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (7, 'Стелс-геймплей', 'stealth', 'Dishonored 2', 'Улучшенная система скрытности с новыми механиками укрытия и обнаружения.', '{"Новая система укрытий","Улучшенный ИИ врагов","Разные уровни обнаружения","Звук влияет на скрытность"}', '{"Используйте Тёмное зрение для планирования","Следите за конусами обзора врагов","Перемещайтесь в присяде в опасных зонах","Используйте окружение для отвлечения"}', '2026-01-31 06:03:13.892902', NULL);
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (8, 'Достижения Ghost и Clean Hands', 'achievements', 'Dishonored 2', 'Классические достижения за прохождение без убийств и обнаружения. Доступны для обоих персонажей.', '{"Ghost: пройти без обнаружения","Clean Hands: никого не убивать","Можно получить за одно прохождение","Работает для Эмили и Корво"}', '{"Часто сохраняйтесь","Изучайте карты перед действием","Используйте способности для стелса","Нокаутированные враги не считаются убийством"}', '2026-01-31 06:03:13.892902', NULL);
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (9, 'Костяные амулеты и крафт', 'customization', 'Dishonored 2', 'Новая система крафта костяных амулетов. Можно создавать свои амулеты с выбранными эффектами.', '{"Можно носить до 10 амулетов","Крафт новых амулетов","Комбинирование эффектов","Уникальные черты Эмили и Корво"}', '{"Собирайте все костяные осколки","Экспериментируйте с комбинациями","Подбирайте амулеты под стиль игры","Некоторые комбинации дают синергию"}', '2026-01-31 06:03:13.892902', NULL);
INSERT INTO public.game_mechanics (id, title, category, game, description, effects, tips, created_at, image) VALUES (10, 'Руны и древо способностей', 'progression', 'Dishonored 2', 'Расширенное древо способностей для Эмили и Корво. Больше рун и вариантов развития персонажей.', '{"Уникальные способности для каждого персонажа","Больше улучшений чем в первой игре","Можно переиграть с другим персонажем","Разблокируются новые способности по сюжету"}', '{"Планируйте развитие заранее","Ищите все руны с помощью Сердца","Разные способности для разных стилей","Некоторые способности синергируют между собой"}', '2026-01-31 06:03:13.892902', NULL);


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.games (id, title, subtitle, release_date, description, img, video, audio, info, developer, publisher, created_at) VALUES (1, 'Dishonored', 'Revenge Solves Everything', '2012-10-09', 'Dishonored - это immersive sim от Arkane Studios, где вы играете за Корво Аттано, бывшего Королевского Защитника, ложно обвиненного в убийстве Императрицы.', NULL, NULL, NULL, NULL, 'Arkane Studios', 'Bethesda Softworks', '2026-01-23 15:28:01.575982');
INSERT INTO public.games (id, title, subtitle, release_date, description, img, video, audio, info, developer, publisher, created_at) VALUES (2, 'Dishonored 2', 'Take Back What''s Yours', '2016-11-11', 'Dishonored 2 - продолжение культовой игры, где вы можете выбрать между Корво Аттано и его дочерью Эмили Кэлдвин.', NULL, NULL, NULL, NULL, 'Arkane Studios', 'Bethesda Softworks', '2026-01-23 15:28:01.575982');


--
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (4, 'Меч', 'weapon', 'common', 'Dishonored', NULL, 'Основное оружие ближнего боя. Быстрые и смертельные удары.', '{"Блокирование атак","Бесшумные убийства","Быстрые комбо"}', 'С самого начала игры', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (5, 'Арбалет', 'weapon', 'common', 'Dishonored', NULL, 'Бесшумное оружие дальнего боя с различными видами болтов.', '{"Бесшумная стрельба","Различные типы болтов","Высокая точность"}', 'Получен от Пьеро', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (6, 'Пистолет', 'weapon', 'uncommon', 'Dishonored', NULL, 'Шумное огнестрельное оружие. Эффективно против бронированных врагов.', '{"Высокий урон","Пробивает броню","Привлекает внимание"}', 'Получен от Пьеро', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (7, 'Гранаты', 'weapon', 'uncommon', 'Dishonored', NULL, 'Взрывные устройства для уничтожения групп врагов.', '{"Урон по площади","Отбрасывает врагов","Уничтожает препятствия"}', 'Можно купить у Пьеро', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (8, 'Пружинная бритва', 'weapon', 'rare', 'Dishonored', NULL, 'Смертельная ловушка. Убивает первого, кто активирует её.', '{"Смертельный урон","Устанавливается как ловушка","Работает на расстоянии"}', 'Можно купить у Пьеро', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (9, 'Эликсир здоровья', 'consumable', 'common', 'Dishonored', NULL, 'Эликсир Соколова. Восстанавливает здоровье при использовании.', '{"Восстанавливает 50% здоровья","Мгновенное действие"}', 'Находятся по всему миру', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (10, 'Эликсир маны', 'consumable', 'common', 'Dishonored', NULL, 'Духовное средство Пьеро. Восстанавливает ману для способностей.', '{"Восстанавливает 50% маны","Необходим для способностей"}', 'Находятся по всему миру', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (11, 'Костяные амулеты', 'enhancement', 'uncommon', 'Dishonored', NULL, 'Мистические артефакты с пассивными бонусами различных эффектов.', '{"Пассивные бонусы","Различные эффекты","Можно носить до 6 штук"}', 'Находятся с помощью Сердца', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (12, 'Руны', 'currency', 'rare', 'Dishonored', NULL, 'Используются для получения и улучшения сверхъестественных способностей.', '{"Открывают новые способности","Улучшают существующие","Ограниченное количество"}', 'Находятся с помощью Сердца', '2026-01-31 05:32:39.277095');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (13, 'Меч', 'weapon', 'common', 'Dishonored 2', NULL, 'Основное оружие ближнего боя. Улучшенная версия с новыми возможностями.', '{"Блокирование и контратаки","Бесшумные убийства","Различные комбо"}', 'С самого начала игры', '2026-01-31 05:48:35.744274');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (14, 'Арбалет', 'weapon', 'common', 'Dishonored 2', NULL, 'Бесшумное оружие дальнего боя с улучшенными характеристиками.', '{"Бесшумная стрельба","Улучшенные типы болтов","Точность выше чем в первой части"}', 'Получен от Антона Сокольского', '2026-01-31 05:48:35.744274');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (15, 'Пистолет', 'weapon', 'uncommon', 'Dishonored 2', NULL, 'Улучшенное огнестрельное оружие с новыми модификациями.', '{"Высокий урон","Новые типы патронов","Возможность улучшения"}', 'Получен от Антона Сокольского', '2026-01-31 05:48:35.744274');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (16, 'Шокирующие мины', 'weapon', 'uncommon', 'Dishonored 2', NULL, 'Нелетальные ловушки для оглушения врагов.', '{Оглушение,"Не убивает","Можно переставлять"}', 'Можно купить', '2026-01-31 05:48:35.744274');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (17, 'Липкие гранаты', 'weapon', 'rare', 'Dishonored 2', NULL, 'Взрывные устройства, прилипающие к поверхностям.', '{"Урон по площади","Прилипают к целям","Таймер детонации"}', 'Можно купить', '2026-01-31 05:48:35.744274');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (18, 'Раствор Аддермайра', 'consumable', 'uncommon', 'Dishonored 2', NULL, 'Улучшенный эликсир, восстанавливающий здоровье и ману одновременно.', '{"Восстанавливает 50% здоровья","Восстанавливает 50% маны","Комбинированное действие"}', 'Находятся по всему миру', '2026-01-31 05:48:35.744274');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (19, 'Костяные амулеты', 'enhancement', 'uncommon', 'Dishonored 2', NULL, 'Мистические артефакты с пассивными бонусами. Можно создавать свои.', '{"Пассивные бонусы","Возможность крафта","Можно носить до 10 штук"}', 'Находятся с помощью Сердца', '2026-01-31 05:48:35.744274');
INSERT INTO public.items (id, title, category, rarity, game, image, description, effects, location, created_at) VALUES (20, 'Руны', 'currency', 'rare', 'Dishonored 2', NULL, 'Используются для получения способностей Эмили или Корво.', '{"Открывают новые способности","Улучшают существующие","Больше рун чем в первой части"}', 'Находятся с помощью Сердца', '2026-01-31 05:48:35.744274');


--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (7, 'Карнака', 'Dishonored 2', NULL, 'city', 'Южный портовый город Империи, известный своей архитектурой и теплым климатом.', '{"Ветряные мельницы","Пылевые бури","Дворец герцога",Санаторий}', '/assets/img/locations/dishonored2/dust_district.jpg', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (8, 'Особняк герцога', 'Dishonored 2', 'Аристократический', 'building', 'Роскошная резиденция герцога Абеле и Делайлы Копперспун.', '{"Механический особняк","Сейфовая комната","Королевская галерея"}', '/assets/img/locations/dishonored2/grand_palace.jpg', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (9, 'Часовой механизм', 'Dishonored 2', 'Промышленный', 'building', 'Огромное механическое устройство, созданное гениальным изобретателем Кириным Джиндошем.', '{"Механические солдаты","Трансформирующиеся комнаты",Головоломки}', '/assets/img/locations/dishonored2/clockwork_mansion.jpg', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (10, 'Институт Аддермайра', 'Dishonored 2', 'Медицинский', 'building', 'Психиатрическая лечебница, где проводятся жестокие эксперименты.', '{"Камеры пациентов",Операционные,Подземелья}', '/assets/img/locations/dishonored2/addermire_institute.jpg', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (11, 'Пыльный округ', 'Dishonored 2', 'Бедняцкий', 'district', 'Беднейший район Карнаки, страдающий от кровопийц и банд.', '{"Заражение кровопийцами","Гнездо Гнили","Чёрный рынок"}', '/assets/img/locations/dishonored2/dust_district.jpg', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (1, 'Дануолл', 'Dishonored', NULL, 'city', 'Столица Островной Империи, индустриальный мегаполис викторианской эпохи, охваченный чумой.', '{"Башня Дануолла","Китобойные станции","Районы трущоб","Крысиная чума"}', '/assets/img/locations/dishonored1/dunwall_tower.png', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (4, 'Высокое Аббатство', 'Dishonored', 'Религиозный', 'building', 'Штаб-квартира Ордена Вечнозрителей, место религиозной власти.', '{Библиотека,"Офис Верховного Смотрителя","Зал поклонения"}', '/assets/img/locations/dishonored1/dunwall_tower_fortified.jpg', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (5, 'Особняк Буль', 'Dishonored', 'Аристократический', 'building', 'Роскошная резиденция леди Буль, центр светской жизни знати.', '{"Бальный зал","Подвал с пытками","Тайные проходы"}', '/assets/img/locations/dishonored1/golden_cat_exterior.jpg', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (6, 'Скотобойня', 'Dishonored', 'Промышленный', 'building', 'Заброшенная скотобойня, превращённая в базу убийц Даудю.', '{"Тренировочный зал","Алтарь Аутсайдера","Секретные пути"}', '/assets/img/locations/dishonored1/flooded_district.png', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (2, 'Башня Дануолла', 'Dishonored', 'Правительственный', 'building', 'Резиденция Императрицы и центр политической власти Империи.', '{"Тронный зал","Покои Эмили","Королевский сад"}', '/assets/img/locations/dishonored1/dunwall_tower.png', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (3, 'Паб "Гончие Ямы"', 'Dishonored', 'Промышленный', 'building', 'Штаб-квартира Верных заговорщиков, старый паб в промышленном районе.', '{"Комната планирования",Арсенал,"Мастерская Пьеро"}', '/assets/img/locations/dishonored1/hound_pits_front.png', '2026-01-31 00:34:17.799789');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (12, 'Золотой Кот', 'Dishonored', 'Дистиллерный округ', 'building', 'Роскошный бордель в Дистиллерном округе, популярное заведение среди дануолльской знати.', NULL, '/assets/img/locations/dishonored1/golden_cat_exterior.jpg', '2026-01-31 04:13:26.654155');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (13, 'Затопленный район', 'Dishonored', 'Затопленный округ', 'district', 'Район Дануолла, опустошённый чумой и затопленный. Здесь обитают чумные крысы и зараженные.', NULL, '/assets/img/locations/dishonored1/flooded_district.png', '2026-01-31 04:13:26.654155');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (14, 'Тюрьма Колдридж', 'Dishonored', 'Река Рэт', 'building', 'Охраняемая тюрьма на острове в реке Рэт, где Корво был заключён после убийства императрицы.', NULL, '/assets/img/locations/dishonored1/coldridge_prison_front.jpg', '2026-01-31 04:13:26.654155');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (15, 'Рудшор Гейт', 'Dishonored', 'Затопленный округ', 'landmark', 'Ворота в Затопленный район, последний оплот городской стражи перед заражённой зоной.', NULL, '/assets/img/locations/dishonored1/rudshore_gate.png', '2026-01-31 04:13:26.654155');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (16, 'Центральный Рудшор', 'Dishonored', 'Рудшор', 'district', 'Торговый район с китобойными станциями, центр промышленности Дануолла.', NULL, '/assets/img/locations/dishonored1/central_rudshore.jpg', '2026-01-31 04:13:26.654155');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (17, 'Часовой Особняк', 'Dishonored 2', 'Карнака', 'building', 'Механическое чудо, созданное Кирином Джиндошем - особняк с трансформирующимися комнатами.', NULL, '/assets/img/locations/dishonored2/clockwork_mansion.jpg', '2026-01-31 04:13:26.662254');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (18, 'Королевская консерватория', 'Dishonored 2', 'Карнака', 'building', 'Музыкальная академия Карнаки, захваченная ведьмами Делайлы.', NULL, '/assets/img/locations/dishonored2/royal_conservatory.png', '2026-01-31 04:13:26.662254');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (19, 'Поместье Стилтона', 'Dishonored 2', 'Карнака', 'building', 'Заброшенный особняк Арамиса Стилтона, место, где время можно изменить.', NULL, '/assets/img/locations/dishonored2/stilton_manor_exterior.jpg', '2026-01-31 04:13:26.662254');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (20, 'Великий Дворец', 'Dishonored 2', 'Карнака', 'building', 'Резиденция герцога Луки Абеле, величественный дворец в центре Карнаки.', NULL, '/assets/img/locations/dishonored2/grand_palace.jpg', '2026-01-31 04:13:26.662254');
INSERT INTO public.locations (id, name, game, district, type, description, notable_features, image, created_at) VALUES (21, 'Дредфул Вейл', 'Dishonored 2', 'Море', 'ship', 'Корабль Билли Лёрк, служащий мобильной базой для Корво и Эмили.', NULL, '/assets/img/locations/dishonored2/dreadful_wale.jpg', '2026-01-31 04:13:26.662254');


--
-- Data for Name: powers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (7, 'Искривление времени', 'Time', 2, 'Dishonored', NULL, 'Замедление или остановка времени вокруг Корво.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Корво Аттано', 2, '60%', 3);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (9, 'Пожирающая стая', 'Offensive', 1, 'Dishonored', NULL, 'Призыв стаи прожорливых крыс для атаки врагов.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Корво Аттано', 2, '40%', 2);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (10, 'Притяжение', 'Control', 1, 'Dishonored', NULL, 'Притягивает предметы и врагов на расстоянии.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Корво Аттано', 1, '20%', 1);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (11, 'Дальняя хватка', 'Movement', 1, 'Dishonored 2', NULL, 'Притягивает Эмили к отдалённым точкам или притягивает врагов к ней.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Эмили Кэлдвин', 2, '20%', 1);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (12, 'Теневая поступь', 'Stealth', 2, 'Dishonored 2', NULL, 'Превращение в неуязвимую тень, способную проходить сквозь узкие щели.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Эмили Кэлдвин', 2, '60%', 3);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (13, 'Домино', 'Control', 2, 'Dishonored 2', NULL, 'Связывает врагов, заставляя их разделять одну судьбу.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Эмили Кэлдвин', 2, '40%', 2);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (14, 'Гипноз', 'Control', 2, 'Dishonored 2', NULL, 'Призывает духа Бездны для отвлечения и заколдовывания врагов.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Эмили Кэлдвин', 2, '50%', 3);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (15, 'Двойник', 'Offensive', 3, 'Dishonored 2', NULL, 'Создаёт копию Эмили, способную сражаться и использовать способности.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Эмили Кэлдвин', 2, '80%', 4);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (16, 'Призыв убийц', 'Summon', 2, 'Dishonored', NULL, 'Призывает убийц из группы Даудю для помощи в бою.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Даудю', 2, '50%', 2);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (17, 'Стоп времени', 'Time', 2, 'Dishonored', NULL, 'Полная остановка времени, уникальная версия способности Корво.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Даудю', 1, '80%', 3);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (18, 'Проворство', 'Passive', 1, 'Dishonored', NULL, 'Увеличивает скорость перемещения и высоту прыжка.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Все персонажи', 2, '0%', 1);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (19, 'Кровожадность', 'Passive', 2, 'Dishonored', NULL, 'Адреналиновый режим, замедляющий время при обнаружении.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Все персонажи', 2, '0%', 2);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (20, 'Теневое убийство', 'Passive', 1, 'Dishonored', NULL, 'Убитые тела мгновенно превращаются в пепел.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Все персонажи', 1, '0%', 1);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (4, 'Скачок', 'Movement', 1, 'Dishonored', '/assets/img/powers/dishonored1/blink.png', 'Мгновенная телепортация на короткое расстояние. Фундаментальная способность для перемещения.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Корво Аттано', 2, '20%', 1);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (5, 'Тёмное зрение', 'Perception', 1, 'Dishonored', '/assets/img/powers/dishonored1/dark_vision.png', 'Позволяет видеть живых существ сквозь стены и их поле зрения.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Корво Аттано', 2, '20%', 1);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (6, 'Вселение', 'Control', 2, 'Dishonored', '/assets/img/powers/dishonored1/possession.png', 'Вселение в тела животных и людей для скрытного перемещения.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Корво Аттано', 2, '60%', 2);
INSERT INTO public.powers (id, title, type, cost, game, image, description, upgrades, "character", created_at, character_name, max_level, mana_cost, rune_cost) VALUES (8, 'Порыв ветра', 'Offensive', 1, 'Dishonored', '/assets/img/powers/dishonored1/windblast.png', 'Мощная волна воздуха, отбрасывающая врагов и объекты.', NULL, NULL, '2026-01-31 00:34:17.807225', 'Корво Аттано', 2, '40%', 2);


--
-- Name: characters_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.characters_id_seq', 19, true);


--
-- Name: factions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.factions_id_seq', 7, true);


--
-- Name: game_mechanics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.game_mechanics_id_seq', 10, true);


--
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.games_id_seq', 2, true);


--
-- Name: items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.items_id_seq', 20, true);


--
-- Name: locations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.locations_id_seq', 21, true);


--
-- Name: powers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.powers_id_seq', 20, true);


--
-- PostgreSQL database dump complete
--

\unrestrict p33UeuI0F1Ltak8GDaVMCb5jroQ8SIxoU65ANSsGBAYF5Cz17zfOhskyh2kJMMN

